import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Creer Coach Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={`${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="min-h-screen">{children}</main>
            <Toaster richColors />
            {/* <footer className="bg-muted/50 py-12">
              <div className="text-gray-200 container text-center">
                <p>In Development Mode </p>
              </div>
            </footer> */}
            <footer className="bg-muted/50 border-t border-border py-12">
              <div className="container text-center space-y-3 text-sm text-muted-foreground">
                <p>
                  Built by <span className="font-semibold">Team NextStep</span>{" "}
                  · Final Year Project 2026
                </p>

                <p>React · Next.js · Tailwind CSS · AI APIs · NeonDB</p>

                <p className="text-xs">
                  © 2026 NextStep AI. All rights reserved.
                </p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
